<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CatPaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('cat__paises')->insert(['paisnombre' => 'Australia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Austria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Azerbaiyán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Anguilla','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Argentina','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Armenia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bielorrusia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Belice','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bélgica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bermudas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bulgaria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Brasil','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Reino Unido','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Hungría','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Vietnam','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Haiti','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Guadalupe','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Alemania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Países Bajos, Holanda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Grecia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Georgia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Dinamarca','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Egipto','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Israel','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'India','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Irán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Irlanda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'España','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Italia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Kazajstán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Camerún','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Canadá','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Chipre','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Kirguistán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'China','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Costa Rica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Kuwait','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Letonia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Libia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Lituania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Luxemburgo','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'México','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Moldavia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Mónaco','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Nueva Zelanda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Noruega','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Polonia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Portugal','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Reunión','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Rusia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'El Salvador','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Eslovaquia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Eslovenia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Surinam','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Estados Unidos','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Tadjikistan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Turkmenistan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Islas Turcas y Caicos','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Turquía','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Uganda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Uzbekistán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Ucrania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Finlandia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Francia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'República Checa','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Suiza','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Suecia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Estonia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Corea del Sur','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Japón','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Croacia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Rumanía','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Hong Kong','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Indonesia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Jordania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Malasia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Singapur','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Taiwan','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bosnia y Herzegovina','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bahamas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Chile','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Colombia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Islandia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Corea del Norte','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Macedonia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Malta','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Pakistán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Papúa-Nueva Guinea','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Perú','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Filipinas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Arabia Saudita','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Tailandia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Emiratos árabes Unidos','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Groenlandia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Venezuela','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Zimbabwe','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Kenia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Algeria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Líbano','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Botsuana','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Tanzania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Namibia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Ecuador','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Marruecos','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Ghana','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Siria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Nepal','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Mauritania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Seychelles','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Paraguay','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Uruguay','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Congo (Brazzaville)','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Cuba','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Albania','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Nigeria','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Zambia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Mozambique','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Angola','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Sri Lanka','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Etiopía','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Túnez','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bolivia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Panamá','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Malawi','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Liechtenstein','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bahrein','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Barbados','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Chad','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Man, Isla de','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Jamaica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Malí','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Madagascar','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Senegal','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Togo','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Honduras','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'República Dominicana','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Mongolia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Irak','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Sudáfrica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Aruba','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Gibraltar','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Afganistán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Andorra','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Antigua y Barbuda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bangladesh','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Benín','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Bután','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Islas Virgenes Británicas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Brunéi','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Burkina Faso','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Burundi','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Camboya','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Cabo Verde','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Comores','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Congo (Kinshasa)','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Cook, Islas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Costa de Marfil','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Djibouti, Yibuti','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Timor Oriental','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Guinea Ecuatorial','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Eritrea','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Feroe, Islas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Fiyi','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Polinesia Francesa','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Gabón','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Gambia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Granada','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Guatemala','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Guernsey','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Guinea','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Guinea-Bissau','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Guyana','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Jersey','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Kiribati','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Laos','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Lesotho','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Liberia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Maldivas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Martinica','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Mauricio','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Myanmar','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Nauru','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Antillas Holandesas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Nueva Caledonia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Nicaragua','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Níger','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Norfolk Island','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Omán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Isla Pitcairn','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Qatar','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Ruanda','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Santa Elena','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'San Cristobal y Nevis','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Santa Lucía','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'San Pedro y Miquelón','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'San Vincente y Granadinas','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Samoa','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'San Marino','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'San Tomé y Príncipe','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Serbia y Montenegro','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Sierra Leona','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Islas Salomón','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Somalia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Sudán','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Swazilandia','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Tokelau','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Tonga','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Trinidad y Tobago','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Tuvalu','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Vanuatu','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Wallis y Futuna','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Sáhara Occidental','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Yemen','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);
DB::table('cat__paises')->insert(['paisnombre' => 'Puerto Rico','created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')]);

    }
}
